version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - npm install
      - sam build
      - sam package --s3-bucket ${ARTIFACT_BUCKET} --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
