version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # or whatever runtime you're using
  build:
    commands:
      - echo "Building the Lambda function"
      - cd src
      - npm install # if you're using Node.js
      - zip -r ../function.zip . # package your function

artifacts:
  files:
    - function.zip
    - appspec.yml
  discard-paths: yes
