version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - 'echo "Using artifact bucket: node-codebuild-artifacts"'
      - "npm install"
      - "sam build"
  post_build:
    commands:
      - "sam deploy --s3-bucket node-codebuild-artifacts --stack-name realeyes-ai-lambda --capabilities CAPABILITY_IAM --parameter-overrides SageMakerEndpointName=pytorch-inference-2024-11-17-20-45-54-605"
      - 'echo "SAM deployment completed on `date`"'

artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*
    - template.yml
  discard-paths: no
